# Generated by Django 2.1.3 on 2018-11-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bobot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tanaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='kriteria',
            name='tanaman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MOORA.Tanaman'),
        ),
        migrations.AddField(
            model_name='bobot',
            name='tanaman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MOORA.Tanaman'),
        ),
    ]
