# Generated by Django 2.1.3 on 2018-11-13 02:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MOORA', '0002_kriteria_periode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobot',
            name='tanaman',
        ),
        migrations.AddField(
            model_name='bobot',
            name='kriteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MOORA.Kriteria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='value',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
