# Generated by Django 2.1.3 on 2018-11-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOORA', '0005_auto_20181113_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='name_kriteria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MOORA.NameKriteria'),
        ),
    ]
