# Generated by Django 2.1.3 on 2018-11-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOORA', '0007_tanaman_name_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanaman',
            name='name_area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MOORA.NameArea'),
        ),
    ]
