# Generated by Django 2.1.3 on 2018-11-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOORA', '0008_auto_20181115_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('tanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MOORA.Tanaman')),
            ],
        ),
    ]
