# Generated by Django 2.1.3 on 2018-11-23 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOORA', '0009_preferensi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatioQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanaman', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='MOORA.Tanaman')),
            ],
        ),
    ]
