# Generated by Django 2.1.3 on 2018-11-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MOORA', '0010_ratioquality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratioquality',
            name='tanaman',
        ),
    ]
