# Generated by Django 2.1.3 on 2018-11-23 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOORA', '0011_remove_ratioquality_tanaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratioquality',
            name='tanaman',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MOORA.Tanaman'),
        ),
    ]
